[package]
name = "dictless-desktop"
version = "0.1.0"
authors = ["Nick Voloshyn <akavolkol@gmail.com>"]

[dependencies]
gtk = { version = "0.3.0", features = ["v3_22"] }
gdk="0.7.0"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
